//
//  TabItemDataMock.swift
//  Water Flowers
//
//  Created by Vladislav Bondarev on 04.12.2021.
//

struct DataMock {
    static let tabItemsDataMock = [TabItemData(image: "leaf",
                                               selectedImage: "leaf.fill",
                                               title: "Your Flowers"),
                                   TabItemData(image: "drop",
                                               selectedImage: "drop.fill",
                                               title: "Need Water"),
                                   TabItemData(image: "gearshape",
                                               selectedImage: "gearshape.fill",
                                               title: "Setting")
    ]
    
    static let flowersDataMock: [Flower] = [Flower(id: "Gerbera1",
                                                   name: "Gerbera_small",
                                                   description: "Gerbera_small Gerbera_small Gerbera_small Gerbera_small",
                                                   urlImage: nil,
                                                   urlMoreInformation: nil),
                                            Flower(id: "Gerbera2",
                                                   name: "Gerbera_big",
                                                   description: "Gerbera_big Gerbera_big Gerbera_big Gerbera_big Gerbera_big",
                                                   urlImage: nil,
                                                   urlMoreInformation: nil),
                                            Flower(id: "Cactus",
                                                   name: "Cactus",
                                                   description: "Cactus Cactus CactusCactus Cactus Cactus Cactus",
                                                   urlImage: nil,
                                                   urlMoreInformation: nil),
                                            Flower(id: "Gerbera12",
                                                   name: "Gerbera_small",
                                                   description: "Gerbera_small Gerbera_small Gerbera_small Gerbera_small",
                                                   urlImage: nil,
                                                   urlMoreInformation: nil),
                                            Flower(id: "Gerbera22",
                                                   name: "Gerbera_big",
                                                   description: "Gerbera_big Gerbera_big Gerbera_big Gerbera_big Gerbera_big",
                                                   urlImage: nil,
                                                   urlMoreInformation: nil),
                                            Flower(id: "Cactus2",
                                                   name: "Cactus",
                                                   description: "Cactus Cactus CactusCactus Cactus Cactus Cactus",
                                                   urlImage: nil,
                                                   urlMoreInformation: nil),
                                            Flower(id: "Gerbera13",
                                                   name: "Gerbera_small",
                                                   description: "Gerbera_small Gerbera_small Gerbera_small Gerbera_small",
                                                   urlImage: nil,
                                                   urlMoreInformation: nil),
                                            Flower(id: "Gerbera23",
                                                   name: "Gerbera_big",
                                                   description: "Gerbera_big Gerbera_big Gerbera_big Gerbera_big Gerbera_big",
                                                   urlImage: nil,
                                                   urlMoreInformation: nil),
                                            Flower(id: "Cactus3",
                                                   name: "Cactus",
                                                   description: "Cactus Cactus CactusCactus Cactus Cactus Cactus",
                                                   urlImage: nil,
                                                   urlMoreInformation: nil),
                                            Flower(id: "Gerbera14",
                                                   name: "Gerbera_small",
                                                   description: "Gerbera_small Gerbera_small Gerbera_small Gerbera_small",
                                                   urlImage: nil,
                                                   urlMoreInformation: nil),
                                            Flower(id: "Gerbera24",
                                                   name: "Gerbera_big",
                                                   description: "Gerbera_big Gerbera_big Gerbera_big Gerbera_big Gerbera_big",
                                                   urlImage: nil,
                                                   urlMoreInformation: nil),
                                            Flower(id: "Cactus4",
                                                   name: "Cactus",
                                                   description: "Cactus Cactus CactusCactus Cactus Cactus Cactus",
                                                   urlImage: nil,
                                                   urlMoreInformation: nil),
                                            Flower(id: "Gerbera15",
                                                   name: "Gerbera_small",
                                                   description: "Gerbera_small Gerbera_small Gerbera_small Gerbera_small",
                                                   urlImage: nil,
                                                   urlMoreInformation: nil),
//                                            Flower(id: "Gerbera25",
//                                                   name: "Gerbera_big",
//                                                   description: "Gerbera_big Gerbera_big Gerbera_big Gerbera_big Gerbera_big",
//                                                   urlImage: nil,
//                                                   urlMoreInformation: nil),
//                                            Flower(id: "Cactus5",
//                                                   name: "Cactus",
//                                                   description: "Cactus Cactus CactusCactus Cactus Cactus Cactus",
//                                                   urlImage: nil,
//                                                   urlMoreInformation: nil),
//                                            Flower(id: "Gerbera16",
//                                                   name: "Gerbera_small",
//                                                   description: "Gerbera_small Gerbera_small Gerbera_small Gerbera_small",
//                                                   urlImage: nil,
//                                                   urlMoreInformation: nil),
//                                            Flower(id: "Gerbera26",
//                                                   name: "Gerbera_big",
//                                                   description: "Gerbera_big Gerbera_big Gerbera_big Gerbera_big Gerbera_big",
//                                                   urlImage: nil,
//                                                   urlMoreInformation: nil),
//                                            Flower(id: "Cactus6",
//                                                   name: "Cactus",
//                                                   description: "Cactus Cactus CactusCactus Cactus Cactus Cactus",
//                                                   urlImage: nil,
//                                                   urlMoreInformation: nil),
//                                            Flower(id: "Gerbera17",
//                                                   name: "Gerbera_small",
//                                                   description: "Gerbera_small Gerbera_small Gerbera_small Gerbera_small",
//                                                   urlImage: nil,
//                                                   urlMoreInformation: nil),
//                                            Flower(id: "Gerbera27",
//                                                   name: "Gerbera_big",
//                                                   description: "Gerbera_big Gerbera_big Gerbera_big Gerbera_big Gerbera_big",
//                                                   urlImage: nil,
//                                                   urlMoreInformation: nil),
//                                            Flower(id: "Cactus7",
//                                                   name: "Cactus",
//                                                   description: "Cactus Cactus CactusCactus Cactus Cactus Cactus",
//                                                   urlImage: nil,
//                                                   urlMoreInformation: nil),
//                                            Flower(id: "Gerbera18",
//                                                   name: "Gerbera_small",
//                                                   description: "Gerbera_small Gerbera_small Gerbera_small Gerbera_small",
//                                                   urlImage: nil,
//                                                   urlMoreInformation: nil),
//                                            Flower(id: "Gerbera28",
//                                                   name: "Gerbera_big",
//                                                   description: "Gerbera_big Gerbera_big Gerbera_big Gerbera_big Gerbera_big",
//                                                   urlImage: nil,
//                                                   urlMoreInformation: nil),
//                                            Flower(id: "Cactus8",
//                                                   name: "Cactus",
//                                                   description: "Cactus Cactus CactusCactus Cactus Cactus Cactus",
//                                                   urlImage: nil,
//                                                   urlMoreInformation: nil),
    ]
}
